version: "3"
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  web:
    image: scribubble-backend
    build: .
    command: "npm start"
    ports:
      - "4000:4000"
    depends_on:
      - "mongo"
    volumes: 
      - .:/usr/src/app/scribubble-backend
